### ISSUE TITLE
NativeAOT-LLVM: package publishing is not working

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2120]
Last package:

![image](https://user-images.githubusercontent.com/2720041/208110732-bed8cde5-15ed-4aad-8542-f174ec26dace.png)

Some merge mistake I presume.

**Comment by yowl** [comment]
This is the problem behind https://github.com/dotnet/runtimelab/issues/2073

**Comment by jkotas** [comment]
It is failing with:

/eng/pipelines/official/stages/publish.yml (Line: 38, Col: 31): Unexpected parameter 'publishAssetsImmediately'

**Comment by yowl** [comment]
Thanks, I see I took that change when changing the image.  I guess I can revert it until we merge the corresponding change to `publish-build-assets.yml`

**Comment by jkotas** [comment]
The next problem is that it is trying to run Windows Wasm build on Ubuntu build image. Does it ring any bells?

**Comment by yowl** [comment]
maybe its dropping into 
```
 ${{ if eq(parameters.platform.pool, '') }}:
    # The default VM host AzDO pool. This should be capable of running Docker containers: almost all
    # source-build builds run in Docker, including the default managed platform.
    pool:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: NetCore-Public
        demands: ImageOverride -equals Build.Ubuntu.1804.Amd64.Open
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        name: NetCore1ESPool-Internal
        demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
```
in source-build.yml.   Does it say what the step/job was?

**Comment by yowl** [comment]
Or maybe
```
- ${{ if containsValue(parameters.platforms, 'Browser_wasm') }}:
  - template: xplat-setup.yml
    parameters:
      jobTemplate: ${{ parameters.jobTemplate }}
      helixQueuesTemplate: ${{ parameters.helixQueuesTemplate }}
      variables: ${{ parameters.variables }}
      osGroup: Browser
      archType: wasm
      targetRid: browser-wasm
      platform: Browser_wasm
      container:
        image: ubuntu-18.04-webassembly-20210707133424-12f133e
```
as `Browser_wasm` is a subset `Browser_wasm_win`
