### ISSUE TITLE
NativeAOT-LLVM: package publishing broken

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2539]
HI @jkotas, could you please post the current package publishing error, the merge has broken it again?

Thanks,

**Comment by jkotas** [comment]
It is failing with

![image](https://github.com/dotnet/runtimelab/assets/6668460/23135f23-0bdc-4e6b-a711-6f861bd70d7c)

I do not think that it was broken by the merge. 

We are required to switch to standardized YAML templates, and it looks like that the branches that have not switched yet fail the official builds now.

@agocke Could you please confirm that the above error is caused by missing official templates?

If it is the case, the fix is going to be to take another merge to pick up changes like https://github.com/dotnet/runtime/pull/99433 and then fix things up.

**Comment by yowl** [comment]
I've started the next merge, as mentioned above, there are yml changes.  Will we be able to swtich to these new jobs do you think:
```
          - template: /eng/pipelines/common/platform-matrix.yml
            parameters:
              jobTemplate: /eng/pipelines/common/global-build-job.yml
              helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
              buildConfig: checked
              platforms:
              - linux_x64
              - windows_x64
              - Browser_wasm_win
              - wasi_wasm_win
              jobParameters:
                timeoutInMinutes: 300
                buildArgs: -s clr.aot+libs+nativeaot.packages -c debug -rc $(_BuildConfig)
                postBuildSteps:
                  - template: /eng/pipelines/common/templates/runtimes/build-runtime-tests-and-send-to-helix.yml
                    parameters:
                      creator: dotnet-bot
                      testRunNamePrefixSuffix: CoreCLR_$(_BuildConfig)
```
i.e. the `helix-queues-setup.yml` and `build-runtime-tests-and-send-to-helix.yml`?  I will try `global-build-job.yml` to see how it goes.
